# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ~iamdash.com
email: public@iamdash.com
description: > # this means to ignore newlines until "baseurl:"
  Home page of Dave Ashman.
  Web developer living in beautiful British North West.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.iamdash.com" # the base hostname & protocol for your site
twitter_username: _iamdash
github_username:  iamdash

# Build settings
markdown: kramdown
